In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import robust_scale
from scipy.stats import norm

In [15]:
def robust_z(x):
    coefficient = norm.ppf(0.75)-norm.ppf(0.25)
    robust_z_score = robust_scale(x)*coefficient

    return robust_z_score

In [19]:
X = pd.Series([ 1., -2.,  2., -2.,  1.,  3., 4.,  1., -2.])
X

0    1.0
1   -2.0
2    2.0
3   -2.0
4    1.0
5    3.0
6    4.0
7    1.0
8   -2.0
dtype: float64

In [20]:
robust_scale(X)

array([ 0.  , -0.75,  0.25, -0.75,  0.  ,  0.5 ,  0.75,  0.  , -0.75])

In [28]:
x_array = np.array(X).reshape(-1, 1)
x_array

array([[ 1.],
       [-2.],
       [ 2.],
       [-2.],
       [ 1.],
       [ 3.],
       [ 4.],
       [ 1.],
       [-2.]])

In [29]:
scaler = RobustScaler().fit(x_array)
scaler

RobustScaler()

In [31]:
scaler.transform(x_array)

array([[ 0.  ],
       [-0.75],
       [ 0.25],
       [-0.75],
       [ 0.  ],
       [ 0.5 ],
       [ 0.75],
       [ 0.  ],
       [-0.75]])

In [13]:
data = np.concatenate((np.random.uniform(low=5.0, high=10.0, size=100),
                       np.random.normal(loc=5.0, scale=1.0, size=100)))
data

array([6.38531735, 9.92050562, 8.54420587, 9.38318967, 7.19128385,
       8.70474248, 8.17236124, 5.67594583, 7.83215406, 8.12995022,
       9.1904848 , 5.99622048, 5.49368161, 9.47820041, 9.18837786,
       6.32585507, 5.10792007, 8.40409199, 7.74182017, 5.53208607,
       8.03806561, 5.70127905, 6.60295662, 8.4397091 , 8.9611865 ,
       6.05713824, 9.74321142, 9.42598489, 5.37668859, 9.61201221,
       5.35335112, 9.60602791, 6.56626149, 7.01345949, 9.09161995,
       6.35602027, 5.43204047, 7.17429079, 6.35063186, 7.79644074,
       5.50777684, 8.34217889, 6.07100019, 7.99674013, 8.14880298,
       5.03669027, 9.30244301, 8.3790243 , 8.4504228 , 9.73679101,
       9.43321311, 5.62052781, 5.84019716, 6.89253843, 7.17040865,
       8.66436264, 7.50507832, 7.21636602, 5.6294987 , 5.00187596,
       7.99717763, 9.96320434, 6.26628256, 7.32798908, 8.75317102,
       9.35859884, 5.39601367, 6.83027537, 9.56819113, 5.56813748,
       8.23135174, 5.20321738, 8.84641332, 6.18167274, 6.33647